#!/bin/sh

firstrun_file=/var/lib/firstrun

get_config_option() {
        option="$1"

        [ -f /etc/ssh/sshd_config ] || return

        # TODO: actually only one '=' allowed after option
        perl -lne '
                s/[[:space:]]+/ /g; s/[[:space:]]+$//;
                print if s/^[[:space:]]*'"$option"'[[:space:]=]+//i' \
           /etc/ssh/sshd_config
}

# Create host keys
host_keys_required() {
	hostkeys="$(get_config_option HostKey)"
	if [ "$hostkeys" ]; then
		echo "$hostkeys"
	else
		# No HostKey directives at all, so the server picks some
		# defaults depending on the setting of Protocol.
		protocol="$(get_config_option Protocol)"
		[ "$protocol" ] || protocol=1,2
		if echo "$protocol" | grep 1 >/dev/null; then
			echo /etc/ssh/ssh_host_key
		fi
		if echo "$protocol" | grep 2 >/dev/null; then
			echo /etc/ssh/ssh_host_rsa_key
			echo /etc/ssh/ssh_host_dsa_key
			echo /etc/ssh/ssh_host_ecdsa_key
			echo /etc/ssh/ssh_host_ed25519_key
		fi
	fi
}

create_key() {
	msg="$1"
	shift
	hostkeys="$1"
	shift
	file="$1"
	shift

	if echo "$hostkeys" | grep -x "$file" >/dev/null && \
	   [ ! -f "$file" ] ; then
		echo -n $msg
		ssh-keygen -q -f "$file" -N '' "$@"
		echo
		if which restorecon >/dev/null 2>&1; then
			restorecon "$file" "$file.pub"
		fi
		ssh-keygen -l -f "$file.pub"
	fi
}

create_keys() {
	hostkeys="$(host_keys_required)"

	create_key "Creating SSH1 key; this may take some time ..." \
		"$hostkeys" /etc/ssh/ssh_host_key -t rsa1

	create_key "Creating SSH2 RSA key; this may take some time ..." \
		"$hostkeys" /etc/ssh/ssh_host_rsa_key -t rsa
	create_key "Creating SSH2 DSA key; this may take some time ..." \
		"$hostkeys" /etc/ssh/ssh_host_dsa_key -t dsa
	create_key "Creating SSH2 ECDSA key; this may take some time ..." \
		"$hostkeys" /etc/ssh/ssh_host_ecdsa_key -t ecdsa
	create_key "Creating SSH2 ED25519 key; this may take some time ..." \
		"$hostkeys" /etc/ssh/ssh_host_ed25519_key -t ed25519
}

# Reconfigure basic things, like timezone and keyboard layout
dpkg-reconfigure console-data locales tzdata

# Reset the root password
while true
do
	newpasswd=$(whiptail --passwordbox "Enter a new root password, or 'Cancel' to leave the password as 'kosagi'" 10 60 3>&1 1>&2 2>&3)
	if [ $? -ne 0 ]
	then
		break
	fi
	newpasswd2=$(whiptail --passwordbox "Re-enter the password just to make sure, or 'Cancel' to leave the password as 'kosagi'" 10 60 3>&1 1>&2 2>&3)
	if [ $? -ne 0 ]
	then
		break
	fi

	if [ "${newpasswd}" != "${newpasswd2}" ]
	then
		whiptail --msgbox "Passwords do not match.  Please try again." 10 60
		continue
	fi

	if [ -z "${newpasswd}" ]
	then
		if whiptail --yesno "Are you sure you want to set a blank root password?" 10 60
		then
			passwd -d root
			break
		fi
		continue
	fi

	echo "root:${newpasswd}" | /usr/sbin/chpasswd
	if [ $? -ne 0 ]
	then
		whiptail --msgbox "An error occurred while changing the root password." 10 60
		continue
	fi
	break
done

# Set up a new user account
/usr/bin/user-setup

# If a new user was created, they'll have the user id of 1000.  Add them
# to various interesting groups.
if grep -q :1000: /etc/passwd
then
	newid=$(grep :1000: /etc/passwd | cut -d: -f1)
	usermod -G dialout,sudo,audio,video,pulse,i2c,systemd-journal,systemd-timesync,systemd-network,systemd-resolve,scanner,bluetooth,i2c,pulse-access "${newid}"
fi

# Come up with a hostname.  wordlist.txt contains a one-line header, followed
# by a padded, spaced list of interesting words.
# 1) Strip off the header
# 2) Convert the space-padding into linefeeds, deduplicating spaces
# 3) Randomly order the list
# 4) Take the top two words
# 5) Convert the linefeed into a hyphen
# 6) Remove the trailing hyphen
# 7) Prefix the word "novena-"
while true
do
	wordlist="/usr/share/novena-firstrun/wordlist.txt"
	namechars=2
	default_hostname=$(sed 1d < "${wordlist}" | \
		    tr -s ' ' '\n' | \
		    sort -R | \
		    head -n ${namechars} | \
		    tr '\n' '-' | \
		    sed 's/-$//' | \
		    awk '{print "novena-"$0}')
	hostname=$(whiptail --title="Set Hostname" --inputbox "Enter your hostname, or press Enter to use the default, randomized, auto-generated one:" 10 60 "${default_hostname}" --nocancel 3>&1 1>&2 2>&3)
	if hostname "${hostname}"
	then
		echo "${hostname}" > /etc/hostname
		sed -i "s/localhost/localhost ${hostname}/" /etc/hosts
		echo "Your new hostname is ${hostname}"

		# Restart avahi to pick up new name
		systemctl restart avahi-daemon.service
		break;
	fi
done

# Recreate SSH keys separately here, because otherwise it hangs following
# the dpkg-reconfigure of openssh-server.
# We must have a hostname set before we do this.
create_keys

# Set up Debian mirrors
cat > /etc/apt/sources.list <<EOF
deb http://ftp.us.debian.org/debian jessie main contrib non-free
deb-src http://ftp.us.debian.org/debian jessie main contrib non-free
deb http://security.debian.org/ jessie/updates main contrib non-free
deb-src http://security.debian.org/ jessie/updates main contrib non-free
EOF

if whiptail --title="Run netselect-apt" --yesno "Would you like to run a speed test to determine the best Debian mirrors for you to use?" 10 60
then
	netselect-apt -s -o /etc/apt/sources.list
else
	whiptail --title="Run netselect-apt" --msgbox "Okay.  You will be set up to use the US mirror.\n\nTo change this later, run 'netselect-apt'." 10 60
fi

if whiptail --title="Enable Lightdm" --yesno "Would you like to enable graphical logins?" 10 60
then
	systemctl enable lightdm.service
else
	systemctl disable lightdm.service
fi

# All done, remove the "firstrun" file so we don't run again next boot.
rm -f "${firstrun_file}"
